package presentacion.vistas;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import presentacion.controladores.PrincipalController;
import presentacion.modelo.Game;

/**
 *
 * @author David Bohorquez
 */
public class PrincipalView extends javax.swing.JFrame {

    private Game myGame;
    private PrincipalController controlador;
    private ImageIcon imgWindow;

    public PrincipalView(Game game) {
        myGame = game;

        initComponents();

        fix();
        asignarListners();
    }

    public void fix() {
        setSize(800, 400);
        setLocationRelativeTo(null);

        getControlador();

        imgWindow = new ImageIcon(getClass().getResource("/recursos/images/menu.jpg"));
    }

    public void asignarListners() {
        //addMouseListener(getControlador());
        //addMouseMotionListener(getControlador());
        lblClose.addMouseListener(getControlador());
        lblPlay.addMouseListener(getControlador());
    }

    public PrincipalController getControlador() {
        if (controlador == null) {
            controlador = new PrincipalController(this);
        }

        return controlador;
    }

    public Game getMyGame() {
        return myGame;
    }

    public JLabel getLblWindow() {
        return lblWindow;
    }

    public JLabel getLblClose() {
        return lblClose;
    }

    public JLabel getLblPlay() {
        return lblPlay;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblWindow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);
        getContentPane().add(lblClose);
        lblClose.setBounds(760, 0, 30, 30);
        getContentPane().add(lblPlay);
        lblPlay.setBounds(270, 270, 60, 60);

        lblWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/images/menu.jpg"))); // NOI18N
        lblWindow.setOpaque(true);
        getContentPane().add(lblWindow);
        lblWindow.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblWindow;
    // End of variables declaration//GEN-END:variables
}
